apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gateway.name" . }}
    helm.sh/chart: {{ include "gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: {{ .Values.gateway.port }}
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gateway.name" . }}
    helm.sh/chart: {{ include "gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ include "gateway.fullname" . }}
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            port:
              number: {{ .Values.service.port }}
            host: {{ include "gateway.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local


