apiVersion: v1
kind: ConfigMap
metadata:
  name: statistics-service
  labels:
    {{- include "statistics-service.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "files/application.yml").AsConfig | nindent 2 }}