apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "piggymetrics.fullname" . }}-istio-vsvc-config
  labels:
    {{- include "piggymetrics.labels" . | nindent 4 }}
data:
  {{- tpl (.Files.Glob "files/istio-vsvc.yaml").AsConfig . | nindent 2 }}