{{- if .Values.global.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.existingSecret }}
  labels:
    app.kubernetes.io/name: {{ include "piggymetrics.name" . }}
    helm.sh/chart: {{ include "piggymetrics.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  postgresql-user: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  {{- if .Values.postgresql.postgresqlPassword }}
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{- else }}
  postgresql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}