{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "piggymetrics.serviceAccount.name" . }}
  labels:
    {{- include "piggymetrics.labels" . | nindent 4 }}
{{- end }}