{{- if .Values.kafka.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.kafka.configMap }}
  labels:
    {{- include "pgm-dependencies.labels" . | nindent 4 }}
data:
  kafka-brokers: {{ include "pgm-dependencies.kafka.brokers" . }}
{{- end }}