{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.postgresql.secret }}
  labels:
    {{- include "pgm-dependencies.labels" . | nindent 4 }}
type: Opaque
data:
  pgm-postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- if .Values.keycloak.enabled }}
  {{- if .Values.keycloak.keycloak.persistence.dbPassword }}
  {{ .Values.keycloak.keycloak.persistence.existingSecretKey }}: {{ .Values.keycloak.keycloak.persistence.dbPassword | b64enc | quote }}
  {{- else }}
  {{ .Values.keycloak.keycloak.persistence.existingSecretKey }}: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}