{{- if .Values.keycloak.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-realm-secret
  labels:
    {{- include "pgm-dependencies.labels" . | nindent 4 }}
type: Opaque
data:
  {{- (.Files.Glob "files/pgm-realm.json").AsSecrets | nindent 2 }}
{{- end }}