apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service
  labels:
    app.kubernetes.io/name: {{ include "account-service.name" . }}
    helm.sh/chart: {{ include "account-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- (.Files.Glob "files/application.yml").AsConfig | nindent 2 }}