apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "files/application.yml").AsConfig | nindent 2 }}