apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.accountService.host }}
  labels:
    app.kubernetes.io/name: {{ include "account-service.name" . }}
    helm.sh/chart: {{ include "account-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.global.accountService.port }}
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "account-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
