spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:piggymetrics}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:secret}

    hikari:
      maximum-pool-size: 3

  jmx:
    enabled: false

  jooq:
    sql-dialect: postgres_10

  liquibase:
    default-schema: statistics_service

  cloud:
    stream:
      bindings:
        input:
          destination: ${ACCOUNT_EVENT_TOPIC:account-events}
          content-type: application/x-protobuf

grpc:
  server:
    port: 9090