dependencies:
  - name: pgm-frontend
    repository: file://../pgm-frontend
    version: 0.1.0
    condition: pgm-frontend.enabled
  - name: api-gateway
    repository: file://../api-gateway
    version: 0.1.0
    condition: api-gateway.enabled
  - name: account-service
    repository: file://../account-service
    version: 0.1.0
    condition: account-service.enabled
  - name: notification-service
    repository: file://../notification-service
    version: 0.1.0
    condition: notification-service.enabled
  - name: statistics-service
    repository: file://../statistics-service
    version: 0.1.0
    condition: statistics-service.enabled