# Default values for piggymetrics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

gatewayPort: 80

kubectl:
  image: lachlanevenson/k8s-kubectl:latest
  imagePullPolicy: IfNotPresent

pgm-frontend:
  enabled: true

api-gateway:
  enabled: true

account-service:
  enabled: true

notification-service:
  enabled: true

statistics-service:
  enabled: true

serviceAccount:
  create: true
role:
  create: true